ASSUME CS: CODE, DS: DATA
CODE SEGMENT
    START: MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    MOV CX, COUNT
    MOV DI, OFFSET STRING
    MOV BL, 00H
    MOV AL, BYTE1
    SCAN1: NOP
    SCASB
    JZ XXX
    INC BL
    LOOP SCAN1
    XXX: MOV AH, 4CH
    INT 21H
CODE ENDS

DATA SEGMENT
    BYTE1 EQU 25H
    COUNT EQU 06H
    STRING DB 12H, 13H, 20H, 20H, 25H, 21H
DATA ENDS

END START