ASSUME CS: CODE, DS: DATA
DATA SEGMENT
    NUM DD 335A379BH
    BYTE_COUNT EQU 04
DATA ENDS

CODE SEGMENT
    START: MOV AX, DATA
    MOV DS, AX
    MOV DH, BYTE_COUNT
    XOR AL, AL
    MOV CL, 00
    MOV SI, OFFSET NUM
    NEXT_BYTE: ADD AL, [SI]
    JP EVENP
    INC CL
    EVENP: INC SI
    MOV AL, 00
    DEC DH
    JNZ NEXT_BYTE
    MOV DL, 00
    RCR CL, 1
    JNC CLEAR
    INC DL
    CLEAR: MOV AH, 4CH
    INT 21H
CODE ENDS

END START