ASSUME CS: CODE, DS: DATA
DATA SEGMENT
    MESSAGE DB 0DH, 0AH, " THE STUDY OF MICROPROCESSORS IS INTERSETING. ", 0DH, 0AH, "$"
DATA ENDS

CODE SEGMENT
    START: MOV AX, DATA
    MOV DS, AX
    MOV AH, 09H
    MOV DX, OFFSET MESSAGE
    INT 21H
    MOV AH, 4CH
    INT 21H
CODE ENDS

END START
                    