ASSUME CS: CODE, DS: DATA
DATA SEGMENT
    OPR1 EQU 98H
    OPR2 EQU 49H
    PROD DW 01 DUP<00>
    DIVS DW 01 DUP<00>
DATA ENDS 
CODE SEGMENT
    START: MOV AX, DATA
    MOV DS, AX
    MOV BL, OPR2
    XOR AL, AL
    MOV AL, OPR1
    MUL BL
    MOV WORD PTR PROD, AX
    XOR AH, AH
    MOV AL, OPR1
    DIV BL
    MOV WORD PTR DIVS, AX
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START
