ASSUME CS: CODE, DS: DATA
DATA SEGMENT
    CODELIST DB 36,48,59,45,23,12,19,20,21,00
    CHAR EQU 05
    CODEC DB 01H DUP<?>
DATA ENDS   

CODE SEGMENT
    START: MOV AX, DATA
    MOV DS, AX
    MOV BX, OFFSET CODELIST
    MOV AL, CHAR
    XLAT
    MOV BYTE PTR CODEC, AL
    MOV AH, 4CH
    INT 21H
CODE ENDS

END START