ASSUME CS: CODE, DS: DATA
DATA SEGMENT
    OPR1 EQU 98H
    OPR2 EQU 49H
    SUM DW 01 DUP<00>
    SUBT DW 01 DUP<00>
DATA ENDS 

CODE SEGMENT
    START: MOV AX, DATA
    MOV DS, AX
    MOV BL, OPR2
    XOR AL, AL
    MOV AL, OPR1
    ADD AL,BL
    DAA
    MOV BYTE PTR SUM, AL
    JNC MSBO
    INC [SUM+1]
    MSBO: XOR AL, AL
    MOV AL, OPR1
    SUB AL, BL
    DAS
    MOV BYTE PTR SUBT, AL
    JNB MSB1
    INC [SUBT+1]
    MSB1: MOV AH, 4CH
    INT 21H
CODE ENDS

END START
