ASSUME CS:CODE, DS:DATA

DATA SEGMENT
    OPR1 DW 1234H
    OPR2 DW 0002H
    RESULT DW 01 DUP<?>
    
CODE SEGMENT
    START: MOV AX,DATA
    MOV DS,AX
    MOV AX,OPR1
    MOV BX,OPR2
    CLC
    ADD AX,BX
    MOV DI,OFFSET RESULT
    MOV [DI],AX
    MOV AH,4CH
    INT 21H
    CODE ENDS

END START