ASSUME CS:DATA,DS:DATA
DATA SEGMENT
    SERIES DB 52H,23H,
    COUNT EQU 100D
    RESULT DW 01H DUP<?>
    DATA ENDS
CODE SEGMENT
START: MOV AX,DATA
    MOV DS,AX
    MOV CX,COUNT
    XOR AX,AX
    XOR BX,BX
    MOV SI,OFFSET SERIES
AGAIN: MOV BL,[SI]
    ADD AX,BX
    INC SI
    DEC CX
    JNZ AGAIN
    MOV DI,OFFSET RESULT
    MOV [DI],AX
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START